### ISSUE TITLE
GUI acting as CLI proxy

### ISSUE THREAD

**Issue by CasperStaahl** [P6-AAU-23/server#51]

**Comment by CasperStaahl** [comment]
![Image](https://user-images.githubusercontent.com/72453813/230072124-90e85d01-5f04-45af-866a-65e712e4899b.png)

**Comment by RedToad0** [comment]
https://github.com/chriskiehl/Gooey
https://towardsdatascience.com/how-to-transform-your-command-line-app-into-a-user-friendly-gui-98c207564324
